import { defineAliasMap } from '../core/aliases.js';

export const flx6CanonicalAliases = defineAliasMap([
  { raw: 'xfader', canonical: 'mixer.crossfader' },
  { raw: 'xfader_slider', canonical: 'mixer.crossfader' },
  { raw: 'crossfader', canonical: 'mixer.crossfader' },

  { raw: 'slider_ch1', canonical: 'mixer.channel.1.fader' },
  { raw: 'slider_ch2', canonical: 'mixer.channel.2.fader' },
  { raw: 'slider_ch3', canonical: 'mixer.channel.3.fader' },
  { raw: 'slider_ch4', canonical: 'mixer.channel.4.fader' },

  { raw: 'trim_ch1', canonical: 'mixer.channel.1.gain' },
  { raw: 'trim_ch2', canonical: 'mixer.channel.2.gain' },
  { raw: 'trim_ch3', canonical: 'mixer.channel.3.gain' },
  { raw: 'trim_ch4', canonical: 'mixer.channel.4.gain' },
  { raw: 'trim_1', canonical: 'mixer.channel.1.gain' },
  { raw: 'trim_2', canonical: 'mixer.channel.2.gain' },
  { raw: 'trim_3', canonical: 'mixer.channel.3.gain' },
  { raw: 'trim_4', canonical: 'mixer.channel.4.gain' },

  { raw: 'eq_hi_ch1', canonical: 'mixer.channel.1.eq.high' },
  { raw: 'eq_hi_ch2', canonical: 'mixer.channel.2.eq.high' },
  { raw: 'eq_hi_ch3', canonical: 'mixer.channel.3.eq.high' },
  { raw: 'eq_hi_ch4', canonical: 'mixer.channel.4.eq.high' },
  { raw: 'hi_1', canonical: 'mixer.channel.1.eq.high' },
  { raw: 'hi_2', canonical: 'mixer.channel.2.eq.high' },
  { raw: 'hi_3', canonical: 'mixer.channel.3.eq.high' },
  { raw: 'hi_4', canonical: 'mixer.channel.4.eq.high' },

  { raw: 'eq_mid_ch1', canonical: 'mixer.channel.1.eq.mid' },
  { raw: 'eq_mid_ch2', canonical: 'mixer.channel.2.eq.mid' },
  { raw: 'eq_mid_ch3', canonical: 'mixer.channel.3.eq.mid' },
  { raw: 'eq_mid_ch4', canonical: 'mixer.channel.4.eq.mid' },
  { raw: 'mid_1', canonical: 'mixer.channel.1.eq.mid' },
  { raw: 'mid_2', canonical: 'mixer.channel.2.eq.mid' },
  { raw: 'mid_3', canonical: 'mixer.channel.3.eq.mid' },
  { raw: 'mid_4', canonical: 'mixer.channel.4.eq.mid' },

  { raw: 'eq_low_ch1', canonical: 'mixer.channel.1.eq.low' },
  { raw: 'eq_low_ch2', canonical: 'mixer.channel.2.eq.low' },
  { raw: 'eq_low_ch3', canonical: 'mixer.channel.3.eq.low' },
  { raw: 'eq_low_ch4', canonical: 'mixer.channel.4.eq.low' },
  { raw: 'low_1', canonical: 'mixer.channel.1.eq.low' },
  { raw: 'low_2', canonical: 'mixer.channel.2.eq.low' },
  { raw: 'low_3', canonical: 'mixer.channel.3.eq.low' },
  { raw: 'low_4', canonical: 'mixer.channel.4.eq.low' },

  { raw: 'filter_ch1', canonical: 'mixer.channel.1.filter' },
  { raw: 'filter_ch2', canonical: 'mixer.channel.2.filter' },
  { raw: 'filter_ch3', canonical: 'mixer.channel.3.filter' },
  { raw: 'filter_ch4', canonical: 'mixer.channel.4.filter' },
  { raw: 'filter_1', canonical: 'mixer.channel.1.filter' },
  { raw: 'filter_2', canonical: 'mixer.channel.2.filter' },
  { raw: 'filter_3', canonical: 'mixer.channel.3.filter' },
  { raw: 'filter_4', canonical: 'mixer.channel.4.filter' },

  { raw: 'cue_ch1', canonical: 'mixer.channel.1.cue' },
  { raw: 'cue_ch2', canonical: 'mixer.channel.2.cue' },
  { raw: 'cue_ch3', canonical: 'mixer.channel.3.cue' },
  { raw: 'cue_ch4', canonical: 'mixer.channel.4.cue' },
  { raw: 'headphone_cue_1', canonical: 'mixer.channel.1.cue' },
  { raw: 'headphone_cue_2', canonical: 'mixer.channel.2.cue' },
  { raw: 'headphone_cue_3', canonical: 'mixer.channel.3.cue' },
  { raw: 'headphone_cue_4', canonical: 'mixer.channel.4.cue' },

  { raw: 'slider_TEMPO_L', canonical: 'deck.left.tempo.fader' },
  { raw: 'slider_TEMPO_R', canonical: 'deck.right.tempo.fader' },

  { raw: 'jog_L', canonical: 'deck.left.jog.motion' },
  { raw: 'jog_R', canonical: 'deck.right.jog.motion' },
  { raw: 'jog_L_touch', canonical: 'deck.left.jog.touch' },
  { raw: 'jog_R_touch', canonical: 'deck.right.jog.touch' },
  { raw: 'jogcut_L', canonical: 'deck.left.jog.cutter' },
  { raw: 'jogcut_R', canonical: 'deck.right.jog.cutter' },
  { raw: 'jogcut_x5F_L', canonical: 'deck.left.jog.cutter' },
  { raw: 'jogcut_x5F_R', canonical: 'deck.right.jog.cutter' },

  { raw: 'play_L', canonical: 'deck.left.transport.play' },
  { raw: 'play_R', canonical: 'deck.right.transport.play' },
  { raw: 'cue_L', canonical: 'deck.left.transport.cue' },
  { raw: 'cue_R', canonical: 'deck.right.transport.cue' },
  { raw: 'load_1', canonical: 'deck.left.transport.load' },
  { raw: 'load_2', canonical: 'deck.right.transport.load' },
  { raw: 'load_3', canonical: 'deck.left.transport.load' },
  { raw: 'load_4', canonical: 'deck.right.transport.load' },
  { raw: 'btn_LOAD_1', canonical: 'deck.left.transport.load' },
  { raw: 'btn_LOAD_2', canonical: 'deck.right.transport.load' },
  { raw: 'btn_LOAD_3', canonical: 'deck.left.transport.load' },
  { raw: 'btn_LOAD_4', canonical: 'deck.right.transport.load' },
  { raw: 'beatsync_L', canonical: 'deck.left.transport.sync' },
  { raw: 'beatsync_R', canonical: 'deck.right.transport.sync' },
  { raw: 'decks_L', canonical: 'deck.left.transport.layer' },
  { raw: 'decks_R', canonical: 'deck.right.transport.layer' },
  { raw: 'btn_DECK_SELECT_L', canonical: 'deck.left.transport.layer' },
  { raw: 'btn_DECK_SELECT_R', canonical: 'deck.right.transport.layer' },
  { raw: 'loop_in_L', canonical: 'deck.left.loop.in' },
  { raw: 'loop_in_R', canonical: 'deck.right.loop.in' },
  { raw: 'loop_out_L', canonical: 'deck.left.loop.out' },
  { raw: 'loop_out_R', canonical: 'deck.right.loop.out' },
  { raw: 'loop_x5F_in_x5F_L', canonical: 'deck.left.loop.in' },
  { raw: 'loop_x5F_in_x5F_R', canonical: 'deck.right.loop.in' },
  { raw: 'loop_x5F_out_x5F_L', canonical: 'deck.left.loop.out' },
  { raw: 'loop_x5F_out_x5F_R', canonical: 'deck.right.loop.out' },
  { raw: 'reloop_exit_L', canonical: 'deck.left.loop.reloop_exit' },
  { raw: 'reloop_exit_R', canonical: 'deck.right.loop.reloop_exit' },
  { raw: 'select_loop_call_LL', canonical: 'deck.left.loop.call.backward' },
  { raw: 'select_loop_call_RL', canonical: 'deck.left.loop.call.forward' },
  { raw: 'select_loop_call_LR', canonical: 'deck.right.loop.call.backward' },
  { raw: 'select_loop_call_RR', canonical: 'deck.right.loop.call.forward' },
  { raw: 'loop_memory_L', canonical: 'deck.left.loop.memory' },
  { raw: 'loop_memory_R', canonical: 'deck.right.loop.memory' },

  { raw: 'hotcue_L', canonical: 'deck.left.pad_mode.hotcue' },
  { raw: 'hotcue_R', canonical: 'deck.right.pad_mode.hotcue' },
  { raw: 'sampler_L', canonical: 'deck.left.pad_mode.sampler' },
  { raw: 'sampler_R', canonical: 'deck.right.pad_mode.sampler' },
  { raw: 'beatjump_L', canonical: 'deck.left.pad_mode.beatjump' },
  { raw: 'beatjump_R', canonical: 'deck.right.pad_mode.beatjump' },
  { raw: 'padfx_L', canonical: 'deck.left.pad_mode.fx' },
  { raw: 'padfx_R', canonical: 'deck.right.pad_mode.fx' },
  { raw: 'mode_HOTCUE_L', canonical: 'deck.left.pad_mode.hotcue' },
  { raw: 'mode_HOTCUE_R', canonical: 'deck.right.pad_mode.hotcue' },
  { raw: 'mode_SAMPLER_L', canonical: 'deck.left.pad_mode.sampler' },
  { raw: 'mode_SAMPLER_R', canonical: 'deck.right.pad_mode.sampler' },
  { raw: 'mode_BEATJUMP_L', canonical: 'deck.left.pad_mode.beatjump' },
  { raw: 'mode_BEATJUMP_R', canonical: 'deck.right.pad_mode.beatjump' },
  { raw: 'mode_PADFX_L', canonical: 'deck.left.pad_mode.fx' },
  { raw: 'mode_PADFX_R', canonical: 'deck.right.pad_mode.fx' },

  { raw: 'knob_MERGEFX_L', canonical: 'deck.left.fx.quick' },
  { raw: 'knob_MERGEFX_R', canonical: 'deck.right.fx.quick' },
  { raw: 'merge_button_L', canonical: 'deck.left.fx.quick_select' },
  { raw: 'merge_button_R', canonical: 'deck.right.fx.quick_select' },
  { raw: 'btn_MERGEFX_SEL_L', canonical: 'deck.left.fx.quick_select' },
  { raw: 'btn_MERGEFX_SEL_R', canonical: 'deck.right.fx.quick_select' },

  { raw: 'browse_encoder', canonical: 'browser.scroll' },
  { raw: 'browse_encoder_press', canonical: 'browser.push' },
  { raw: 'back', canonical: 'browser.back' },
  { raw: 'view', canonical: 'browser.view' },

  { raw: 'pad_L_1', canonical: 'deck.left.pad.1' },
  { raw: 'pad_L_2', canonical: 'deck.left.pad.2' },
  { raw: 'pad_L_3', canonical: 'deck.left.pad.3' },
  { raw: 'pad_L_4', canonical: 'deck.left.pad.4' },
  { raw: 'pad_L_5', canonical: 'deck.left.pad.5' },
  { raw: 'pad_L_6', canonical: 'deck.left.pad.6' },
  { raw: 'pad_L_7', canonical: 'deck.left.pad.7' },
  { raw: 'pad_L_8', canonical: 'deck.left.pad.8' },

  { raw: 'pad_R_1', canonical: 'deck.right.pad.1' },
  { raw: 'pad_R_2', canonical: 'deck.right.pad.2' },
  { raw: 'pad_R_3', canonical: 'deck.right.pad.3' },
  { raw: 'pad_R_4', canonical: 'deck.right.pad.4' },
  { raw: 'pad_R_5', canonical: 'deck.right.pad.5' },
  { raw: 'pad_R_6', canonical: 'deck.right.pad.6' },
  { raw: 'pad_R_7', canonical: 'deck.right.pad.7' },
  { raw: 'pad_R_8', canonical: 'deck.right.pad.8' },
]);

export default flx6CanonicalAliases;
